### ISSUE TITLE
Plugin

### ISSUE THREAD

**Issue by amit177** [weeryan17/Discord-Groups#5]
The plugin writes everything 2/3 times in the discord and in mc chat.

EDIT: after restarting the server, it stopped sending it.
igns didnt sync tho and all the confirmations ids were the same(01)

**Comment by weeryan17** [comment]
Well the original problem in this issue is solved I'm probably going to close this thread but real quick so you don't have to make another issue. Rename or delete your config so the plugin generate a new config and then copy back over the token and main channel name. The IGN sync is disabled by default and theirs a new config option for it,

**Comment by amit177** [comment]
I did change the "false" to true. it didnt sync the names.

**Comment by weeryan17** [comment]
Sorry for the late response. The bot will only sync names when the user joins the server. If you still have problems than move this over to a different issue.
